/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package animehalloweenprograms.animetrivia;

/**
 *
 * @author Phyllis
 */
public class ControlsQuestionAnswer extends javax.swing.JPanel {

    /**
     * Creates new form ControlsQuestionAnswer
     */
    public ControlsQuestionAnswer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionAnswerText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();

        questionAnswerText.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        questionAnswerText.setForeground(new java.awt.Color(102, 102, 102));
        questionAnswerText.setText("Question");

        questionTextArea.setEditable(false);
        questionTextArea.setColumns(20);
        questionTextArea.setForeground(new java.awt.Color(51, 51, 51));
        questionTextArea.setRows(5);
        jScrollPane2.setViewportView(questionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(questionAnswerText, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(questionAnswerText, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel questionAnswerText;
    private javax.swing.JTextArea questionTextArea;
    // End of variables declaration//GEN-END:variables
}
